version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: grocy-app
    volumes:
      - grocy-code:/var/www/html
      - /container-data/sinali-grocy:/var/www/html/data
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/nginx.Dockerfile
    container_name: grocy-web
    volumes:
      - grocy-code:/var/www/html
    depends_on:
      - app
    restart: unless-stopped

volumes:
  grocy-code:
